services:
  api:
    image: ghcr.io/sakurasm/guangya-media-manager-backend:${IMAGE_TAG:-latest}
    build: !reset null

  worker:
    image: ghcr.io/sakurasm/guangya-media-manager-backend:${IMAGE_TAG:-latest}
    build: !reset null

  web:
    image: ghcr.io/sakurasm/guangya-media-manager-web:${IMAGE_TAG:-latest}
    build: !reset null
